### ISSUE TITLE
Hi Liyan,

### ISSUE THREAD

**Issue by github-liyan** [jfgrim/redis4AppenderLog4j#2]
Hi Liyan,
You find configuration's file for Loj4j in this document : [https://mapr.com/blog/how-log-apache-spark/](https://mapr.com/blog/how-log-apache-spark/)
Add this : (change your server's IP and port, password for redis's user)
log4j.rootLogger=DEBUG, redis
log4j.appender.redis=RedisAppender
log4j.appender.redis.layout=…
log4j.appender.redis.hosts=localhost:6379,10.10.3.3:7000
log4j.appender.redis.password=password
log4j.appender.redis.mode=list
log4j.appender.redis.key=key
log4j.appender.redis.period=500
log4j.appender.redis.batchSize=100
log4j.appender.redis.purgeOnFailure=true
log4j.appender.redis.alwaysBatch=true
log4j.appender.redis.daemonThread=true

You can find in your pom.xml this : 
`<dependency>
	<groupId>com.github.jfgrim</groupId>
	<artifactId>redis4AppenderLog4j</artifactId>
	<version>1.0.0</version>
</dependency>
`

_Originally posted by @jfgrim in https://github.com/jfgrim/redis4AppenderLog4j/issues/1#issuecomment-476085755_

**Comment by github-liyan** [comment]
Let me show you my configuration file
1 pom.xml
        <dependency>
            <groupId>com.github.jfgrim</groupId>
            <artifactId>redis4AppenderLog4j</artifactId>
            <version>1.0.0</version>
        </dependency>
2 log4j.properties

log4j.appender.redis=client.redis.log4jAppender.RedisAppender
log4j.appender.redis.mode=list
log4j.appender.redis.key=redis
log4j.appender.redis.hosts=11.22.233.241:6379
log4j.appender.redis.password=123456
log4j.appender.redis.period=500
log4j.appender.redis.batchSize=100
log4j.appender.redis.purgeOnFailure=true
log4j.appender.redis.alwaysBatch=true
log4j.appender.redis.daemonThread=true
log4j.appender.redis.attemptDelay =3000
log4j.appender.redis.numberRetryToRedis=3
log4j.appender.redis.layout=net.logstash.log4j.JSONEventLayout

**Comment by jfgrim** [comment]
don't forget in our pom.xml this :
`        <dependency>
            <groupId>net.logstash.log4j</groupId>
            <artifactId>jsonevent-layout</artifactId>
            <version>1.7</version>
        </dependency>` 

You use the logstash layout JSONEvent for communicating with redisAppender
